#!/bin/sh
set -eu

: "${NEXTOP_APP_PACKAGE_DIR:?}"
: "${NEXTOP_APP_HOST:?}"
: "${NEXTOP_APP_PORT:?}"
: "${NEXTOP_APP_RUNTIME_DIR:?}"
: "${NEXTOP_APP_DATA_DIR:?}"
: "${NEXTOP_APP_LOG_DIR:?}"
: "${NEXTOP_APP_PYTHON:?}"

mkdir -p "$NEXTOP_APP_RUNTIME_DIR" "$NEXTOP_APP_DATA_DIR" "$NEXTOP_APP_LOG_DIR"
exec "$NEXTOP_APP_PYTHON" "$NEXTOP_APP_PACKAGE_DIR/server.py"
