package defaults

// Code generated by tools/scripts/generate-defaults.mjs. DO NOT EDIT.

var generatedDefaults = generatedDefaultsSpec{
	State: generatedStateDefaults{
		ProductionDirName:    ".nextop",
		DevelopmentDirName:   ".nextop-dev",
		RunDirName:           "run",
		ListenerInfoFileName: "nextopd.listener.json",
	},
}
