// Code generated by runtime/codexproto/internal/codegen. DO NOT EDIT.
// Source codex commit: 6d2168f06ae275d5e1f73cabf935d2bcc8549998

package codexproto

import (
	"context"
	"encoding/json"
	"fmt"
)

// ServerRequestHandler handles requests initiated by the app-server.
type ServerRequestHandler interface {
	AccountChatgptAuthTokensRefresh(ctx context.Context, params ChatgptAuthTokensRefreshParams) (*ChatgptAuthTokensRefreshResponse, error)
	ApplyPatchApproval(ctx context.Context, params ApplyPatchApprovalParams) (*ApplyPatchApprovalResponse, error)
	AttestationGenerate(ctx context.Context, params AttestationGenerateParams) (*AttestationGenerateResponse, error)
	ExecCommandApproval(ctx context.Context, params ExecCommandApprovalParams) (*ExecCommandApprovalResponse, error)
	ItemCommandExecutionRequestApproval(ctx context.Context, params CommandExecutionRequestApprovalParams) (*CommandExecutionRequestApprovalResponse, error)
	ItemFileChangeRequestApproval(ctx context.Context, params FileChangeRequestApprovalParams) (*FileChangeRequestApprovalResponse, error)
	ItemPermissionsRequestApproval(ctx context.Context, params PermissionsRequestApprovalParams) (*PermissionsRequestApprovalResponse, error)
	ItemToolCall(ctx context.Context, params DynamicToolCallParams) (*DynamicToolCallResponse, error)
	ItemToolRequestUserInput(ctx context.Context, params ToolRequestUserInputParams) (*ToolRequestUserInputResponse, error)
	McpServerElicitationRequest(ctx context.Context, params McpServerElicitationRequestParams) (*McpServerElicitationRequestResponse, error)
}

func dispatchServerRequest(ctx context.Context, handler ServerRequestHandler, req JSONRPCRequest) (any, error) {
	switch req.Method {
	case "account/chatgptAuthTokens/refresh":
		var params ChatgptAuthTokensRefreshParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.AccountChatgptAuthTokensRefresh(ctx, params)
	case "applyPatchApproval":
		var params ApplyPatchApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ApplyPatchApproval(ctx, params)
	case "attestation/generate":
		var params AttestationGenerateParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.AttestationGenerate(ctx, params)
	case "execCommandApproval":
		var params ExecCommandApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ExecCommandApproval(ctx, params)
	case "item/commandExecution/requestApproval":
		var params CommandExecutionRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemCommandExecutionRequestApproval(ctx, params)
	case "item/fileChange/requestApproval":
		var params FileChangeRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemFileChangeRequestApproval(ctx, params)
	case "item/permissions/requestApproval":
		var params PermissionsRequestApprovalParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemPermissionsRequestApproval(ctx, params)
	case "item/tool/call":
		var params DynamicToolCallParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemToolCall(ctx, params)
	case "item/tool/requestUserInput":
		var params ToolRequestUserInputParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.ItemToolRequestUserInput(ctx, params)
	case "mcpServer/elicitation/request":
		var params McpServerElicitationRequestParams
		if len(req.Params) > 0 {
			if err := json.Unmarshal(req.Params, &params); err != nil {
				return nil, err
			}
		}
		return handler.McpServerElicitationRequest(ctx, params)
	default:
		return nil, fmt.Errorf("unsupported server request %q", req.Method)
	}
}
